name: crypto_pro_flutter
description: Подписание файлов и сообщений с помощью Crypto Pro
version: 0.1.19
homepage: https://github.com/qscr/crypto_pro_flutter.git

environment:
  sdk: "^3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^1.0.4
  pigeon: ^25.3.2
  test: ^1.25.7

flutter:
  plugin:
    platforms:
      android:
        package: com.a2soft.crypto_pro_flutter
        pluginClass: CryptoProFlutterPlugin
      ios:
        pluginClass: CryptoProFlutterPlugin
